"use client";
import { useEffect, useRef, useState, type FormEvent } from 'react';
import { api } from './api-client';
import type { Employee, Lead, Role, User, MessageTemplate } from './crm-types';

const message = (error:unknown) => error instanceof Error ? error.message : 'Unable to save. Please retry.';
export const roleLabel = (role:Role) => role==='Manager'?'Management':role==='Sales Employee'?'Sales':role;

export function EmployeesPanel({user,employees,reload}:{user:User;employees:Employee[];reload:()=>Promise<void>}) {
  const [editing,setEditing]=useState<Employee|'new'|null>(null);
  const [error,setError]=useState('');const[busy,setBusy]=useState(false);
  const [transfer,setTransfer]=useState<Employee|null>(null);
  const roles:Role[]=user.role==='Reception'?['Sales Employee','Reception','Manager']:['Sales Employee','Reception','Manager','Administrator'];
  const change=async(employee:Employee,patch:Record<string,unknown>)=>{setBusy(true);setError('');try{await api(`/api/employees/${employee.id}`,{method:'PATCH',body:JSON.stringify({version:employee.version,...patch})});await reload();}catch(e){setError(message(e));}finally{setBusy(false);}};
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!editing)return;const data=new FormData(event.currentTarget);const text=(key:string)=>String(data.get(key)??'').trim();setBusy(true);setError('');
    const name=text('displayName');const parts=name.split(/\s+/);const role=text('role');
    const payload={displayName:name,firstName:parts[0],lastName:parts.slice(1).join(' ')||parts[0],email:text('email'),phone:text('phone'),role,ownLeadsOnly:data.get('ownLeadsOnly')==='on',...(data.get('password')?{password:String(data.get('password'))}:{}),...(editing==='new'?{}:{version:editing.version})};
    try{await api(editing==='new'?'/api/employees':`/api/employees/${editing.id}`,{method:editing==='new'?'POST':'PATCH',body:JSON.stringify(payload)});setEditing(null);if(editing!=='new'&&editing.id===user.id&&data.get('password')){window.location.reload();return;}await reload();}catch(e){setError(message(e));}finally{setBusy(false);}
  };
  const deactivate=async(employee:Employee,target?:string)=>{setError('');setBusy(true);try{await api(`/api/employees/${employee.id}/deactivate`,{method:'POST',body:JSON.stringify({transferToUserId:target})});setTransfer(null);await reload();}catch(e){setError(message(e));}finally{setBusy(false);}};
  return <section className="surface operations-employees"><div className="panel-heading"><div><p className="eyebrow">EMPLOYEES</p><h2>People, access & workload</h2></div><button className="primary" onClick={()=>{setError('');setEditing('new');}}>＋ Create profile</button></div>
    <p className="operations-help">“Own leads only” limits a sales employee’s leads, history, tasks and calendar. Management and administrators have full access.</p>
    {error&&<p className="form-error" role="alert">{error}</p>}
    <div className="table-wrap"><table><thead><tr><th>Employee</th><th>Role</th><th>Active leads</th><th>Overdue follow-ups</th><th>New leads</th><th>Tasks due</th><th>Uncontacted</th><th>Visibility</th><th>Manage</th></tr></thead><tbody>{employees.map(e=>{const canEdit=user.role!=='Reception'||e.role==='Sales Employee';return <tr key={e.id}><td><strong>{e.displayName}</strong><small>{e.email}</small>{!e.isActive&&<small>Inactive</small>}</td><td>{roleLabel(e.role)}</td><td>{e.activeLeads}</td><td>{e.overdueLeads}</td><td>{e.newLeads}</td><td>{e.tasksDue}</td><td>{e.uncontactedLeads}</td><td>{e.role==='Sales Employee'?<label className="toggle-label"><input type="checkbox" checked={e.ownLeadsOnly} disabled={busy} onChange={v=>void change(e,{ownLeadsOnly:v.target.checked})}/> Own leads only</label>:<span>All leads</span>}</td><td>{canEdit&&<div className="row-actions"><button onClick={()=>{setError('');setEditing(e);}}>Edit</button>{e.id!==user.id&&(e.isActive?<button disabled={busy} onClick={()=>setTransfer(e)}>Deactivate</button>:<button disabled={busy} onClick={()=>void change(e,{isActive:true})}>Reactivate</button>)}</div>}</td></tr>})}</tbody></table></div>
    <p className="operations-help">Tasks due includes overdue tasks and tasks due today. Uncontacted means no recorded answered call or sent message. Existing ownership is preserved; managers can take a new lead using “Assign to me” when creating it.</p>
    {editing&&<div className="modal-backdrop centered"><form className="new-lead-modal compact-modal" onSubmit={submit}><header><h2>{editing==='new'?'Create profile':'Edit employee'}</h2><button type="button" onClick={()=>setEditing(null)}>×</button></header><div className="form-grid"><label className="wide">Name *<input name="displayName" required minLength={2} defaultValue={editing==='new'?'':editing.displayName}/></label><label>Email *<input name="email" type="email" required defaultValue={editing==='new'?'':editing.email}/></label><label>Phone<input name="phone" defaultValue={editing==='new'?'':editing.phone}/></label><label>Role<select name="role" defaultValue={editing==='new'?'Sales Employee':editing.role}>{(editing!=='new'&&user.role==='Reception'?['Sales Employee'] as Role[]:roles).map(r=><option value={r} key={r}>{roleLabel(r)}</option>)}</select></label><label>{editing==='new'?'Password *':'New password (optional)'}<input name="password" type="password" autoComplete="new-password" minLength={8} required={editing==='new'}/></label><label className="wide toggle-label"><input type="checkbox" name="ownLeadsOnly" defaultChecked={editing==='new'||editing.ownLeadsOnly}/> Sales accounts: show only their assigned leads</label>{error&&<p className="form-error wide" role="alert">{error}</p>}</div><footer><button type="button" onClick={()=>setEditing(null)}>Cancel</button><button className="primary" disabled={busy}>{busy?'Saving…':'Save profile'}</button></footer></form></div>}
    {transfer&&<div className="modal-backdrop centered"><form className="new-lead-modal compact-modal" onSubmit={e=>{e.preventDefault();void deactivate(transfer,String(new FormData(e.currentTarget).get('target')||'')||undefined);}}><header><h2>Deactivate {transfer.displayName}?</h2><button type="button" onClick={()=>setTransfer(null)}>×</button></header><div className="form-grid"><p className="wide">Their history is retained. Transfer any active leads before deactivation.</p>{transfer.activeLeads>0&&<label className="wide">Transfer {transfer.activeLeads} active leads to<select name="target" required defaultValue=""><option value="" disabled>Select employee</option>{employees.filter(e=>e.isActive&&e.id!==transfer.id&&!['Administrator','Manager'].includes(e.role)).map(e=><option key={e.id} value={e.id}>{e.displayName}</option>)}</select></label>}{error&&<p role="alert" className="form-error wide">{error}</p>}</div><footer><button type="button" onClick={()=>setTransfer(null)}>Cancel</button><button className="primary" disabled={busy}>Confirm deactivation</button></footer></form></div>}
  </section>;
}

export function RequirementsPanel({lead,reload}:{lead:Lead;reload:()=>Promise<void>}) {
  const [editing,setEditing]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);const text=(k:string)=>String(d.get(k)||'')||null;const number=(k:string)=>text(k)==null?null:Number(text(k));setBusy(true);setError('');try{await api(`/api/leads/${lead.id}`,{method:'PATCH',body:JSON.stringify({version:lead.version,propertyType:text('propertyType'),preferredLocation:text('preferredLocation'),bedrooms:number('bedrooms'),budgetMin:number('budgetMin'),budgetMax:number('budgetMax'),furnishedPreference:text('furnishedPreference'),moveInDate:text('moveInDate')})});await reload();setEditing(false);}catch(err){setError(message(err));}finally{setBusy(false);}};
  return <section className="info-card requirements-panel"><div className="section-heading"><h3>Property requirements</h3><button onClick={()=>setEditing(!editing)}>{editing?'Cancel':'Edit requirements'}</button></div>{editing?<form className="form-grid" onSubmit={submit}><label>Property type<input name="propertyType" defaultValue={lead.propertyType} placeholder="Apartment, villa, office…"/></label><label>Preferred location<input name="preferredLocation" defaultValue={lead.preferredLocation}/></label><label>Bedrooms<input name="bedrooms" type="number" min={0} max={100} defaultValue={lead.bedrooms??''}/><small>0 for studio</small></label><label>Furnished preference<select name="furnishedPreference" defaultValue={lead.furnishedPreference}><option value="">Not specified</option>{['Furnished','Unfurnished','Partly furnished','No preference'].map(x=><option key={x}>{x}</option>)}</select></label><label>Minimum budget<input name="budgetMin" type="number" min={0} defaultValue={lead.budgetMin??''}/></label><label>Maximum budget<input name="budgetMax" type="number" min={0} defaultValue={lead.budgetMax??''}/></label><label>Move-in date<input name="moveInDate" type="date" defaultValue={lead.moveInDate}/></label>{error&&<p className="wide form-error" role="alert">{error}</p>}<button disabled={busy} className="primary wide">Save requirements</button></form>:<div className="detail-grid two">{[['Property type',lead.propertyType],['Preferred location',lead.preferredLocation],['Bedrooms',lead.bedrooms===0?'Studio':lead.bedrooms],['Minimum budget',lead.budgetMin],['Maximum budget',lead.budgetMax],['Furnished preference',lead.furnishedPreference],['Move-in date',lead.moveInDate]].map(([label,value])=><label key={label}>{label}<strong>{value==null||value===''?'Not specified':String(value)}</strong></label>)}</div>}</section>;
}

export function TemplatesEditor({templates,reload}:{templates:MessageTemplate[];reload:()=>Promise<void>}) {
  const [draft,setDraft]=useState(templates),[error,setError]=useState(''),[saved,setSaved]=useState(false),[busy,setBusy]=useState(false);
  return <form className="surface templates-editor" onSubmit={async e=>{e.preventDefault();setError('');setBusy(true);try{await api('/api/settings',{method:'PATCH',body:JSON.stringify({messageTemplates:draft})});await reload();setSaved(true);}catch(err){setError(message(err));}finally{setBusy(false);}}}><div className="panel-heading"><h2>WhatsApp message templates</h2><button className="primary" disabled={busy}>Save templates</button></div><p className="operations-help">Use {'{name}'}, {'{interest}'}, {'{location}'}, {'{budget}'}, {'{employee}'} and {'{viewing}'}. Employees can edit the generated message before copying it.</p>{draft.map((t,i)=><label key={t.id}>{t.name}<textarea required maxLength={4000} rows={4} value={t.body} onChange={e=>{setSaved(false);setDraft(draft.map((x,n)=>n===i?{...x,body:e.target.value}:x));}}/></label>)}{error&&<p className="form-error" role="alert">{error}</p>}{saved&&<p role="status">Templates saved.</p>}</form>;
}

export function Communications({lead,templates,user,reload,viewing}:{lead:Lead;templates:MessageTemplate[];user:User;reload:()=>Promise<void>;viewing?:string}) {
  const[mode,setMode]=useState<'call'|'whatsapp'|'email'|null>(null),[text,setText]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[copied,setCopied]=useState(false);
  const copyArea=useRef<HTMLTextAreaElement>(null);
  let phone=lead.phone.replace(/\D/g,'');if(phone.startsWith('00'))phone=phone.slice(2);if(phone.startsWith('0')&&phone.length===10)phone='971'+phone.slice(1);
  const render=(body:string)=>body.replace(/\{(\w+)\}/g,(raw,key:string)=>({name:lead.name,interest:lead.interest,location:lead.preferredLocation||'[add location]',budget:lead.budgetMin!=null||lead.budgetMax!=null?`${lead.budgetMin??'…'}–${lead.budgetMax??'…'} AED`:lead.budget!=null?`${lead.budget} AED`:'[add budget]',employee:user.displayName,viewing:viewing?new Date(viewing).toLocaleString('en-AE'):'[add viewing date and time]'}[key]??raw));
  const record=async(type:string,outcome?:string)=>{setBusy(true);setError('');try{await api(`/api/leads/${lead.id}/interactions`,{method:'POST',body:JSON.stringify({type,outcome,summary:type==='call'?`Call outcome: ${outcome}`:type==='whatsapp'?`WhatsApp sent: ${text}`:'Email sent (confirmed by employee)'})});await reload();setMode(null);}catch(e){setError(message(e));}finally{setBusy(false);}};
  return <div className="communications"><div className="profile-actions">{phone&&<><a href={`tel:${phone}`} onClick={()=>{setMode('call');setError('');}}>☎ Call</a><button onClick={()=>{setMode('whatsapp');setText(render(templates[0]?.body??'Hello {name},'));setCopied(false);setError('');}}>◉ WhatsApp</button></>}{lead.email&&<a href={`mailto:${lead.email}`} onClick={()=>setMode('email')}>✉ Email</a>}</div>{mode&&<div className="communication-panel"><div className="section-heading"><h3>{mode==='call'?'Record call outcome':mode==='email'?'Record email':'WhatsApp message'}</h3><button onClick={()=>setMode(null)}>Cancel</button></div>{mode==='call'?<div className="outcome-buttons">{['Answered','No answer','Call back later','Not interested','Wrong number'].map(x=><button key={x} disabled={busy} onClick={()=>void record('call',x)}>{x}</button>)}</div>:mode==='email'?<><p>Record this only after you have sent the email.</p><button disabled={busy} onClick={()=>void record('email')}>I sent the email</button></>:<><label>Template<select onChange={e=>{setText(render(templates.find(t=>t.id===e.target.value)?.body??''));setCopied(false);}}>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><textarea ref={copyArea} rows={5} maxLength={900} value={text} onChange={e=>{setText(e.target.value);setCopied(false);}}/><div className="outcome-buttons"><button onClick={async()=>{try{if(navigator.clipboard&&window.isSecureContext)await navigator.clipboard.writeText(text);else {copyArea.current?.focus();copyArea.current?.select();if(!document.execCommand('copy'))throw Error('Select the message and press Ctrl+C to copy.');}setCopied(true);setError('');}catch(e){setError(message(e));}}}>{copied?'Copied ✓':'Copy message'}</button><a className="primary" target="_blank" rel="noreferrer" href={`https://wa.me/${phone}?text=${encodeURIComponent(text)}`}>Open WhatsApp</a><button disabled={busy||!text.trim()} onClick={()=>void record('whatsapp')}>I sent the message</button></div><small>Opening WhatsApp or copying text does not record contact. Confirm after sending.</small></>}{error&&<p role="alert" className="form-error">{error}</p>}</div>}</div>;
}

type AssignmentNotice={id:number;leadId:number;name:string;interest:string;assignedBy:string;createdAt:string};
export function AssignmentAlerts({user,open}:{user:User;open:(id:number)=>Promise<void>}) {
  const[items,setItems]=useState<AssignmentNotice[]>([]),[expanded,setExpanded]=useState(false),[error,setError]=useState(''),[desktop,setDesktop]=useState(false);
  const seen=useRef(new Set<number>());const native=useRef(new Map<number,Notification>());const current=useRef(items);current.current=items;
  const activate=async(item:AssignmentNotice)=>{try{await open(item.leadId);await api(`/api/notifications/${item.id}/acknowledge`,{method:'POST'});setItems(old=>old.filter(x=>x.id!==item.id));native.current.get(item.id)?.close();native.current.delete(item.id);setError('');}catch(e){setError(message(e));}};
  const activateRef=useRef(activate);activateRef.current=activate;
  useEffect(()=>{let stopped=false;let timer:ReturnType<typeof setTimeout>;const refresh=async()=>{try{const list=await api<AssignmentNotice[]>('/api/notifications');if(stopped)return;setItems(list);setError('');for(const [id,n]of native.current)if(!list.some(x=>x.id===id)){n.close();native.current.delete(id);}for(const item of list){if(!seen.current.has(item.id)&&desktop&&'Notification'in window&&Notification.permission==='granted'){const notice=new Notification('New lead assigned to you',{body:`${item.name} · ${item.interest}`,tag:`lead-assignment-${item.id}`,requireInteraction:true});notice.onclick=()=>{window.focus();void activateRef.current(item);};native.current.set(item.id,notice);seen.current.add(item.id);}}}catch(e){if(!stopped)setError(message(e));}finally{if(!stopped)timer=setTimeout(refresh,15000);}};void refresh();return()=>{stopped=true;clearTimeout(timer);for(const n of native.current.values())n.close();native.current.clear();};},[user.id,desktop]);
  return <div className="assignment-alerts"><button className="notification-trigger" onClick={()=>setExpanded(!expanded)} aria-expanded={expanded}>♢ Assignments {items.length>0&&<b>{items.length}</b>}</button>{expanded&&<section className="notification-panel"><h3>Your assignments</h3><p>Alerts stay here until you open them.</p>{items.map(item=><button className="assignment-item" key={item.id} onClick={()=>void activate(item)}><strong>{item.name}</strong><span>{item.interest}</span><small>Assigned by {item.assignedBy}</small></button>)}{!items.length&&<p>No unread assignments.</p>}{error&&<p role="alert">{error}</p>}<button onClick={async()=>{if(!window.isSecureContext||!('Notification'in window)){setError('For desktop alerts on this network address, run the Windows notifier included with the update. CRM alerts remain available here.');return;}const permission=await Notification.requestPermission();setDesktop(permission==='granted');if(permission!=='granted')setError('Notifications are disabled in this browser. Allow them in site settings.');}}>{desktop?'Desktop alerts enabled':'Enable desktop alerts'}</button><small>Browser desktop alerts require the CRM tab to stay open. Windows/browser settings control how long desktop banners stay visible.</small></section>}</div>;
}
